# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5                      # Nombre de pages à afficher dans la barre de navigation
    default_options:
        page_name: page                # Nom de la variable de requête utilisée pour la pagination
        sort_field_name: sort          # Nom de la variable de requête utilisée pour le tri
        sort_direction_name: direction # Nom de la variable de requête utilisée pour la direction du tri
        distinct: true                 # Utiliser DISTINCT pour éviter les doublons
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig' # Modèle de pagination à utiliser
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # Modèle pour les liens de tri
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'